application: frlrm-187801
version: 20171201t202404
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: views.main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
